package no.northcode.tdd;

import java.util.stream.Stream;
import java.util.Optional;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'andreas' at '30/11/16 23:13' with Gradle 3.2.1
 *
 * @author andreas, @date 30/11/16 23:13
 */
public class Library {

    public static void main(String[] args) {

	

    }
}
